# Generated by Django 5.2.8 on 2025-12-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_therapistprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(
                blank=True,
                null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='status',
            field=models.CharField(
                choices=[
                    ('ACTIVE',
                     'Active'),
                    ('INACTIVE',
                     'Inactive'),
                    ('ON_LEAVE',
                     'On Leave')],
                default='ACTIVE',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(
                choices=[
                    ('ACTIVE',
                     'Active'),
                    ('DISCHARGED',
                     'Discharged')],
                default='ACTIVE',
                max_length=20),
        ),
    ]
