# Generated by Django 5.2.8 on 2025-12-23 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units to assign to patient', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
