# Generated by Django 5.2.8 on 2025-12-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipmentorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='available_quantity',
            field=models.PositiveIntegerField(
                help_text='Units currently available not assigned to patients'),
        ),
    ]
