# Generated by Django 5.2.8 on 2025-12-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipment_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20),
        ),
    ]
