# Generated by Django 5.2.8 on 2025-12-28 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_equipmentorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentorder',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When this order was soft-deleted null = not deleted',
                null=True),
        ),
        migrations.AddField(
            model_name='equipmentorder',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who deleted this order',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deleted_orders',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
