# Generated by Django 5.2.8 on 2025-12-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipmentorder_deleted_at_equipmentorder_deleted_by'), ]

    operations = [
        migrations.AddField(
            model_name='equipmentorder',
            name='notes',
            field=models.TextField(
                blank=True,
                help_text='Special instructions or additional information',
                null=True),
        ),
    ]
