"""
Django settings for quiporder project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------------------------
# SECURITY SETTINGS
# ----------------------------------------------------------------------
SECRET_KEY = config('SECRET_KEY', default='django-insecure-temporary-key')

# SECURITY !! don't run with debug turned on in production! DEBUG = True
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1').split(',')
# Test 500 + 405 run below
# DEBUG = False  # Hard-coded False (ignores .env file) for 500 + 405
# ALLOWED_HOSTS = [ '*']  # 'localhost', '127.0.0.1', Allow all hosts for
# 500 http://127.0.0.1:8000/equipment/test-500/

# ['quiporder.herokuapp.com'] add in prod for allowed hosts

# For Heroku production, set via environment variables:
# DEBUG=False
# ALLOWED_HOSTS=your-app-name.herokuapp.com

# ----------------------------------------------------------------------
# CSRF & SESSION SETTINGS
# ----------------------------------------------------------------------
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# CSRF & Security Settings
if DEBUG:
    # LOCAL DEVELOPMENT
    CSRF_COOKIE_SECURE = False  # True in production only
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False  # No HTTPS locally
    CSRF_COOKIE_HTTPONLY = False  # ← Already set
    CSRF_USE_SESSIONS = False     # ← ADD THIS
    CSRF_TRUSTED_ORIGINS = [
        'http://127.0.0.1:8000',
        'http://localhost:8000',
    ]
else:
    # PRODUCTION (Heroku)
    CSRF_COOKIE_SECURE = True  # in production only keep False for local testing # False
    SESSION_COOKIE_SECURE = True  # Keep False for local testing then True - False
    SECURE_SSL_REDIRECT = True  # DISABLE for local testing with DEBUG=False True - False
    # SECURE_HSTS_SECONDS = 3600  # Comment out for local
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Comment out for local
    # SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # CSRF trusted origins - include local for testing
    CSRF_TRUSTED_ORIGINS = [
        'http://127.0.0.1:8000',
        'http://localhost:8000',
    ]

    # Heroku app URL
    heroku_app_name = config('HEROKU_APP_NAME', default='')
    if heroku_app_name:
        CSRF_TRUSTED_ORIGINS = [f'https://{heroku_app_name}.herokuapp.com']

# ----------------------------------------------------------------------
# INSTALLED APPS
# ----------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'crispy_forms',
    'crispy_bootstrap5',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'users',
    'equipment',
]

# ----------------------------------------------------------------------
# MIDDLEWARE
# ----------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# ----------------------------------------------------------------------
# AUTHENTICATION
# ----------------------------------------------------------------------
AUTH_USER_MODEL = 'users.CustomUser'
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# This tells django-allauth to use OUR custom adapter instead of default
# The adapter handles:
# 1. Blocking public signup (admin-only registration)
# 2. Role-based login redirects (therapist → dashboard, patient → patient
# dashboard)
ACCOUNT_ADAPTER = 'users.adapters.NoSignupAccountAdapter'
# Django-allauth settings
ACCOUNT_EMAIL_VERIFICATION = 'none'

ACCOUNT_EMAIL_REQUIRED = True  # Changed from False

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # Changed from 'username'
# Username requirements
ACCOUNT_USERNAME_REQUIRED = True

# Authentication redirects  after successful login. These are FALLBACK
# values - the custom adapter overrides them
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# ----------------------------------------------------------------------
# STATIC & MEDIA FILES
# ----------------------------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ----------------------------------------------------------------------
# TEMPLATES
# ----------------------------------------------------------------------
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ----------------------------------------------------------------------
# WSGI
# ----------------------------------------------------------------------
WSGI_APPLICATION = 'quiporder.wsgi.application'
ROOT_URLCONF = 'quiporder.urls'

# ----------------------------------------------------------------------
# DATABASE
# ----------------------------------------------------------------------
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('POSTGRES_DB', default='quiporder'),
            'USER': config('POSTGRES_USER'),
            'PASSWORD': config('POSTGRES_PASSWORD'),
            'HOST': config('POSTGRES_HOST', default='localhost'),
            'PORT': config('POSTGRES_PORT', default='5432'),
        }
    }


# ----------------------------------------------------------------------
# PASSWORD VALIDATION
# ----------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ----------------------------------------------------------------------
# INTERNATIONALIZATION
# ----------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ----------------------------------------------------------------------
# EMAIL (dev only)
# ----------------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
